SecondYear/2023-ca298/ca298exam/ca298exam/ca298exam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("examapp.urls")),
    path("admin/", admin.site.urls),
]

SecondYear/2023-ca298/ca298exam/ca298exam/examapp/urls.py
from django.urls import path, include
from . import views
from .forms import * # add o imports at the top of the file

urlpatterns = [
    path('',views.index, name="index"),# mywebsite.com 
    path('register/', views.UserSignupView.as_view(), name="register"),
    path('login/',views.LoginView.as_view(template_name="login.html", authentication_form=UserLoginForm), name='login'),
    path('logout/', views.logout_user, name="logout"),
    path('games/', views.all_games, name='all_games'),
    path('game/<int:game_id>/', views.game_detail, name='game_detail'),
    path('console/<str:platform>/', views.console_games, name='console_games'),
    path('add-to-basket/<int:game_id>/', views.add_to_basket, name='add_to_basket'),
    path('basket/', views.basket_view, name='basket_view'),
    path('add_game/', views.add_game, name='add_game'),   
]

SecondYear/2023-ca298/ca298exam/ca298exam/examapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
# Create your models here.


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

class User(AbstractUser):
    email = models.EmailField('Email', unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()


class Game(models.Model):
    PLATFORM_CHOICES = [
        ('PS5', 'PlayStation 5'),
        ('XBOX', 'Xbox Series X'),
        ('SWITCH', 'Nintendo Switch'),
    ]
    
    GENRE_CHOICES = [
        ('SHOOTER', 'Shooter'),
        ('ACTION', 'Action'),
        ('ADVENTURE', 'Adventure'),
        ('RPG', 'Role-Playing Game'),
    ]
    
    name = models.CharField(max_length=100)
    description = models.TextField()
    platform = models.CharField(max_length=10, choices=PLATFORM_CHOICES)
    genre = models.CharField(max_length=20, choices=GENRE_CHOICES)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    stock = models.PositiveIntegerField()

    def __str__(self):
        return self.name

class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.user.username}'s Basket"


SecondYear/2023-ca298/ca298exam/ca298exam/examapp/forms.py
from .models import *
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import ModelForm, ModelChoiceField
from django.db import transaction



class UserSignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['email', 'password1', 'password2']

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_admin = False
        user.email = self.cleaned_data['email']
        user.username = user.email
        user.save()
        return user


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
    

class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['name', 'description', 'platform', 'genre', 'price', 'stock']

SecondYear/2023-ca298/ca298exam/ca298exam/examapp/views.py
from django.shortcuts import render, get_object_or_404
import random
from .models import *
from .forms import *
from django.views.generic import CreateView
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.db.models import Sum
# Create your views here.


def index(request):
    return render(request, 'index.html')

class UserSignupView(CreateView):
    model = User
    form_class = UserSignupForm
    template_name = 'user_signup.html'

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/')

class UserLoginVGameiew(LoginView):
    template_name='login.html'


def logout_user(request):
    logout(request)
    return redirect("/")

def all_games(request):
    games = Game.objects.all()
    return render(request, 'all_games.html', {'games': games})

def game_detail(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    return render(request, 'game_detail.html', {'game': game})

def console_games(request, platform):
    games = Game.objects.filter(platform=platform)
    return render(request, 'console_games.html', {'games': games})

@login_required
def add_to_basket(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    if request.method == 'POST':
        quantity = int(request.POST.get('quantity'))
        if quantity > game.stock:
            return render(request, 'add_to_basket.html', {'game': game, 'error_message': 'Insufficient stock.'})
        else:
            game.stock -= quantity
            game.save()
            basket_item, created = Basket.objects.get_or_create(user=request.user, game=game)
            if not created:
                basket_item.quantity += quantity
                basket_item.save()
            return redirect('basket_view')
    return render(request, 'add_to_basket.html', {'game': game})

from django.db.models import Sum

@login_required
def basket_view(request):
    basket_items = Basket.objects.filter(user=request.user)
    
    for item in basket_items:
        item.total_price = item.quantity * item.game.price
    
    total_price = sum(item.total_price for item in basket_items)
    
    return render(request, 'basket.html', {'basket_items': basket_items, 'total_price': total_price})
    
@staff_member_required
def add_game(request):
    if request.method == 'POST':
        form = GameForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('all_games')
    else:
        form = GameForm()
    return render(request, 'add_game.html', {'form': form})

SecondYear/2023-ca298/ca298exam/ca298exam/examapp/templates/add_game.html
{% extends 'base.html' %}

{% block title %}
    Add Game
{% endblock %}

{% block extra_css %}
    <style>
        .card-container {
            max-width: 400px;
            margin: 20px auto;
        }

        .card {
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .card-header {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border-top-left-radius: 10px;
            border-top-right-radius: 10px;
        }

        .card-body {
            padding: 20px;
        }

        form {
            margin-top: 20px;
        }

        label {
            display: block;
            margin-bottom: 5px;
            color: #555;
            font-weight: bold;
        }

        input[type="text"],
        input[type="number"],
        select {
            width: calc(100% - 22px); /* Adjusted width to fit within card */
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }

        textarea {
            width: calc(100% - 22px); /* Adjusted width to fit within card */
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            resize: vertical; /* Allow vertical resizing */
            max-height: 200px; /* Limit maximum height */
        }

        button[type="submit"] {
            width: calc(100% - 22px); /* Adjusted width to fit within card */
            padding: 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="card-container">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Add Game</h2>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <label for="id_name">Name:</label>
                    {{ form.name }}
                    <label for="id_description">Description:</label>
                    {{ form.description }}
                    <label for="id_platform">Platform:</label>
                    {{ form.platform }}
                    <label for="id_genre">Genre:</label>
                    {{ form.genre }}
                    <label for="id_price">Price:</label>
                    {{ form.price }}
                    <label for="id_stock">Stock:</label>
                    {{ form.stock }}
                    <button type="submit">Add Game</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

SecondYear/2023-ca298/ca298exam/ca298exam/examapp/templates/add_to_basket.html
{% extends 'base.html' %}
{% block content %}
  <h1>Add {{ game.name }} to Basket</h1>
  <form method="post">
    {% csrf_token %}
    <label for="quantity">Quantity:</label>
    <input type="number" id="quantity" name="quantity" min="1" max="{{ game.stock }}">
    <button type="submit">Add to Basket</button>
  </form>
  {% if error_message %}
    <p>{{ error_message }}</p>
  {% endif %}
{% endblock %}

SecondYear/2023-ca298/ca298exam/ca298exam/examapp/templates/all_games.html
{% extends 'base.html' %}

{% block extra_css %}
    <style>
        .game-card {
            margin-bottom: 20px;
        }

        .game-card .card-body {
            padding: 20px;
        }

        .game-card .card-title {
            font-size: 1.2rem;
            margin-bottom: 10px;
        }

        .game-card .card-text {
            color: #6c757d;
        }

        .scrollable-container {
            max-height: 12500px;
            overflow-y: auto;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="mb-4">All Games</h1>
        <div class="row">
            {% for game in games %}
                <div class="col-md-4">
                    <div class="card game-card">
                        <div class="card-body">
                            <h5 class="card-title">{{ game.name }}</h5>
                            <p class="card-text"><strong>Genre:</strong> {{ game.genre }}</p>
                            <p class="card-text"><strong>Platform:</strong> {{ game.platform }}</p>
                            <p class="card-text"><strong>Price:</strong> €{{ game.price }}</p>
                            <a href="{% url 'game_detail' game.id %}" class="btn btn-primary">View Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <h2 class="mb-4">View Games by Console</h2>
        <div class="scrollable-container">
            <div class="row row-cols-1 row-cols-md-3 g-4">
                <div class="col">
                    <div class="card game-card">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'console_games' 'XBOX' %}">Xbox</a></h5>
                            <p class="card-text">Explore games for Xbox</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card game-card">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'console_games' 'PS5' %}">PlayStation</a></h5>
                            <p class="card-text">Discover games for PlayStation</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card game-card">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'console_games' 'SWITCH' %}">Nintendo</a></h5>
                            <p class="card-text">Browse games for Nintendo</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

SecondYear/2023-ca298/ca298exam/ca298exam/examapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Game Shop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <style>
        .navbar {
            background-color: #007bff; 
            padding: 1rem 2rem;
            border-bottom: 2px solid #fff;
        }

        .navbar-brand {
            font-size: 2rem;
            font-weight: bold;
            color: #fff; 
        }

        .navbar-toggler {
            color: #fff;
            border-color: #fff; 
        }

        .navbar-toggler-icon {
            background-color: #fff; 
        }

        .navbar-nav .nav-item .nav-link {
            font-size: 1.4rem; 
            color: #fff !important; 
            margin: 0 1rem;
            transition: background-color 0.3s, color 0.3s; 
            padding: 0.7rem 1.5rem; 
            border-radius: 10px; 
            background-color: rgba(255, 255, 255, 0.1); 
        }

        .navbar-nav .nav-item .nav-link:hover {
            color: #ffd700 !important; 
            background-color: rgba(255, 255, 255, 0.2); 
        }

        .footer {
            background-color: #007bff; 
            color: #fff; 
            padding: 0.1rem 2rem;
            text-align: center;
            position: fixed;
            bottom: 0;
            width: 100%;
        }
        
        body {
            margin-bottom: 50px; 
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            height: 100vh;
        }
    </style>
        {% block extra_css %}
        {% endblock %}
</head>
<body>

  <nav class="navbar navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Game Shop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ms-auto">
                <a class="nav-link" href="{% url 'all_games' %}">All Games</a>
                {% if user.is_authenticated %}
                    {% if user.is_staff %}
                        <a class="nav-link" href="{% url 'add_game' %}">Add Game</a>
                    {% endif %}
                    <a class="nav-link" href="{% url 'basket_view' %}">Basket</a>
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>


{% block content %}
{% endblock %}

<footer class="footer">
    <div class="container">
        <p>© 2024 Game Shop. All rights reserved.</p>
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-KoAh16cT+yKuSQRHEzoD+Nehbg3Wj6b7cDWCXcWMrre85VhYUwVJQCIU5nFT2b1d" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-n8RYtR3NH/eh8fy2GmPWvU7Q6Z2gg+uUM4P6cH/E5f9c7TD8wSrJpKxC66wwqphx" crossorigin="anonymous"></script>

</body>
</html>

SecondYear/2023-ca298/ca298exam/ca298exam/examapp/templates/basket.html
{% extends 'base.html' %}

{% block extra_css %}
<style>
    .table-responsive {
        overflow-x: auto;
    }

    .table {
        width: 100%;
        margin-bottom: 1rem;
        background-color: transparent;
    }

    .table th,
    .table td {
        padding: 0.75rem;
        vertical-align: top;
        border-top: 1px solid #dee2e6;
    }

    .table thead th {
        vertical-align: bottom;
        border-bottom: 2px solid #dee2e6;
    }

    .table tbody+tbody {
        border-top: 2px solid #dee2e6;
    }

    .table-sm th,
    .table-sm td {
        padding: 0.3rem;
    }

    .table-bordered {
        border: 1px solid #dee2e6;
    }

    .table-bordered th,
    .table-bordered td {
        border: 1px solid #dee2e6;
    }

    .table-bordered thead th,
    .table-bordered thead td {
        border-bottom-width: 2px;
    }

    .table-striped tbody tr:nth-of-type(odd) {
        background-color: rgba(0, 0, 0, 0.05);
    }

    .table-hover tbody tr:hover {
        background-color: rgba(0, 0, 0, 0.075);
    }

    .table-primary,
    .table-primary>th,
    .table-primary>td {
        background-color: #b8daff;
    }

    .table-hover .table-primary:hover {
        background-color: #9fcdff;
    }

    .table-hover .table-primary:hover>td,
    .table-hover .table-primary:hover>th {
        background-color: #9fcdff;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="mb-4">Your Shopping Basket</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                {% for item in basket_items %}
                <tr>
                    <td>{{ item.game.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>€{{ item.game.price }}</td>
                    <td>€{{ item.total_price }}</td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="fw-bold">Total Price:</td>
                    <td class="fw-bold">{{ total_price }}</td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
{% endblock %}

SecondYear/2023-ca298/ca298exam/ca298exam/examapp/templates/console_games.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1 class="mb-4">Games for {{ platform }}</h1>
    <div class="row">
        <div class="col-md-6">
            <ul class="list-group">
                {% for game in games %}
                <li class="list-group-item"><a href="{% url 'game_detail' game.id %}">{{ game.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

SecondYear/2023-ca298/ca298exam/ca298exam/examapp/templates/game_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h1 class="card-title">{{ game.name }}</h1>
                        <p class="card-text">Description: {{ game.description }}</p>
                        <p class="card-text">Platform: {{ game.platform }}</p>
                        <p class="card-text">Genre: {{ game.genre }}</p>
                        <p class="card-text">Price: €{{ game.price }}</p>
                        <p class="card-text">Stock: {{ game.stock }}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">Add to Basket</h2>
                        <form method="post" action="{% url 'add_to_basket' game.id %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="quantity">Quantity:</label>
                                <input type="number" id="quantity" name="quantity" class="form-control" min="1" max="{{ game.stock }}">
                            </div>
                            <button type="submit" class="btn btn-primary">Add to Basket</button>
                        </form>
                        {% if error_message %}
                            <p class="text-danger">{{ error_message }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

SecondYear/2023-ca298/ca298exam/ca298exam/examapp/templates/index.html
{% extends 'base.html' %}

{% block extra_css %}
    <style>
        .jumbotron {
            background-color: #f8f9fa;
            padding: 2rem 1rem;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .jumbotron h3 {
            margin-bottom: 20px;
            font-weight: bold;
            color: #007bff;
        }

        .jumbotron p {
            color: #495057;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h3>Welcome to Ca298 Exam App</h3>
            <p>This is the homepage of the Ca298 exam app.</p>
            <p>Abul Hasan Sheik Madhar Ali</p>
            <p>22390436</p>
        </div>
    </div>
{% endblock %}

SecondYear/2023-ca298/ca298exam/ca298exam/examapp/templates/login.html
{% extends 'base.html' %}

{% block extra_css %}
    <style>
        .form-container {
            max-width: 500px;
            margin: auto;
            padding: 20px;
            background-color: #f9f9f9;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .form-container h2 {
            text-align: center;
            margin-bottom: 20px;
        }

        .form-container form {
            margin-top: 20px;
        }

        .form-container button[type="submit"] {
            width: 100%;
            padding: 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .form-container button[type="submit"]:hover {
            background-color: #0056b3;
        }

        .form-container .mb-3 {
            margin-bottom: 20px;
        }

        .form-container .form-text {
            font-size: 0.8rem;
            color: #6c757d;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="form-container">
        <h2>User Login</h2>

        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                <strong>Error! </strong> Please correct the following errors:
                    <ul>
                    {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    </ul>
            </div>
                        {% endif %}
        <form action="." method="POST">
            {% csrf_token %}
            <div class="mb-3">
                {{ form.username.label_tag }}
                {{ form.username }}
            </div>
            <div class="mb-3">
                {{ form.password.label_tag }}
                {{ form.password }}
            </div>
            <button type="submit">Login</button>
        </form>
    </div>
{% endblock %}


SecondYear/2023-ca298/ca298exam/ca298exam/examapp/templates/user_signup.html
{% extends 'base.html' %}

{% block title %}
    User Signup
{% endblock %}

{% block extra_css %}
    <style>
        .form-container {
            max-width: 500px;
            margin: auto;
            padding: 20px;
            background-color: #f9f9f9;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .form-container h2 {
            text-align: center;
            margin-bottom: 20px;
        }

        .form-container form {
            margin-top: 20px;
        }

        .form-container button[type="submit"] {
            width: 100%;
            padding: 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .form-container button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="form-container">
        <h2>User Signup</h2>

        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            <strong>Error! </strong> Please correct the following errors:
            <ul>
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        
        <form action="." method="POST">
            {% csrf_token %}
            <div class="mb-3">
                {{ form.username.label_tag }}
                {{ form.username }}
                <small id="usernameHelp" class="form-text text-muted">Choose a unique username.</small>
            </div>
            <div class="mb-3">
                {{ form.email.label_tag }}
                {{ form.email }}
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="mb-3">
                {{ form.password1.label_tag }}
                {{ form.password1 }}
            </div>
            <div class="mb-3">
                {{ form.password2.label_tag }}
                {{ form.password2 }}
            </div>
            <button type="submit">Sign Up</button>
        </form>
    </div>
{% endblock %}
